version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flutter_web_app
    ports:
      - "8080:80"
    environment:
      AUTH_URL: "http://localhost:8000"
      FRIENDS_URL: "http://localhost:8001"
      MESSAGES_URL: "http://localhost:8002"
      TEAMS_URL: "http://localhost:8003"